---
abstract: "domms blogging \"engine\""
author:
  - 'Thomas Klausner <domm@cpan.org>'
build_requires:
  File::Temp: 0
  Module::Build: 0.3601
  Module::Pluggable: 0
  Test::File: 0
  Test::Most: 0
  utf8: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Blio
requires:
  DateTime: 0
  DateTime::Format::ISO8601: 0
  DateTime::Format::RFC3339: 0
  Digest::SHA1: 0
  Encode: 0
  File::Copy: 0
  File::ShareDir: 0
  Imager: 0
  Markup::Unified: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::Getopt: 0
  MooseX::SimpleConfig: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  Path::Class::Iterator: 0
  Template: 0
  XML::Atom::SimpleFeed: 0
  namespace::autoclean: 0
  perl: 5.010
  strict: 0
  warnings: 0
resources:
  repository: git+ssh://git.plix.at/home/domm/git/blio.git
version: 2.002
